//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BayetechEntities : DbContext
    {
        public BayetechEntities()
            : base("name=BayetechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleContent> ArticleContent { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<View_ArticleInfo> View_ArticleInfo { get; set; }
        public virtual DbSet<vw_LoginInfo> vw_LoginInfo { get; set; }
    }
}
