//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public long id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string letter { get; set; }
        public Nullable<bool> ishot { get; set; }
        public int parentid { get; set; }
        public short listorder { get; set; }
        public string platform { get; set; }
        public string img { get; set; }
        public bool isdelete { get; set; }
    }
}
