//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRoleInfo
    {
        public int id { get; set; }
        public string gameName { get; set; }
        public Nullable<int> gameLevel { get; set; }
        public string gameProfession { get; set; }
        public string gameService { get; set; }
        public string gameId { get; set; }
        public string userName { get; set; }
        public Nullable<int> listOrder { get; set; }
        public Nullable<int> editTime { get; set; }
        public Nullable<int> addTime { get; set; }
        public string qqLevel { get; set; }
        public string identityInfo { get; set; }
        public string qqFriends { get; set; }
    }
}
