//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Letter { get; set; }
        public bool IsHot { get; set; }
        public int Parentid { get; set; }
        public short Order { get; set; }
        public int Platform { get; set; }
        public string Img { get; set; }
        public bool IsDelete { get; set; }
    }
}
