//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall
    {
        public long itemid { get; set; }
        public int catid { get; set; }
        public long mycatid { get; set; }
        public int areaid { get; set; }
        public byte level { get; set; }
        public byte elite { get; set; }
        public string title { get; set; }
        public string style { get; set; }
        public float fee { get; set; }
        public string introduce { get; set; }
        public string brand { get; set; }
        public decimal price { get; set; }
        public int amount { get; set; }
        public string tag { get; set; }
        public string keyword { get; set; }
        public string pptword { get; set; }
        public int hits { get; set; }
        public int orders { get; set; }
        public int sales { get; set; }
        public int comments { get; set; }
        public string thumb { get; set; }
        public string thumb1 { get; set; }
        public string thumb2 { get; set; }
        public string relate_name { get; set; }
        public string relate_id { get; set; }
        public string relate_title { get; set; }
        public string n1 { get; set; }
        public string n2 { get; set; }
        public string n3 { get; set; }
        public string v1 { get; set; }
        public string v2 { get; set; }
        public string v3 { get; set; }
        public int express_1 { get; set; }
        public string express_name_1 { get; set; }
        public decimal fee_start_1 { get; set; }
        public decimal fee_step_1 { get; set; }
        public int express_2 { get; set; }
        public string express_name_2 { get; set; }
        public decimal fee_start_2 { get; set; }
        public decimal fee_step_2 { get; set; }
        public int express_3 { get; set; }
        public string express_name_3 { get; set; }
        public decimal fee_start_3 { get; set; }
        public decimal fee_step_3 { get; set; }
        public string username { get; set; }
        public short groupid { get; set; }
        public string company { get; set; }
        public short vip { get; set; }
        public byte validated { get; set; }
        public string truename { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string msn { get; set; }
        public string qq { get; set; }
        public string ali { get; set; }
        public string skype { get; set; }
        public string editor { get; set; }
        public int edittime { get; set; }
        public System.DateTime editdate { get; set; }
        public int addtime { get; set; }
        public System.DateTime adddate { get; set; }
        public string ip { get; set; }
        public string template { get; set; }
        public byte status { get; set; }
        public string linkurl { get; set; }
        public string filepath { get; set; }
        public string note { get; set; }
        public string plays { get; set; }
        public string jianshu { get; set; }
        public string jia { get; set; }
        public string leixing { get; set; }
        public string pei { get; set; }
        public string jiaose { get; set; }
        public string anquan { get; set; }
        public string danwei { get; set; }
        public string shouji { get; set; }
        public string qqt { get; set; }
        public int gtid { get; set; }
    }
}
