//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallOrder_Test
    {
        public long MallId { get; set; }
        public string Buyer { get; set; }
        public string Seller { get; set; }
        public long OrderId { get; set; }
        public string OrderTitle { get; set; }
        public string OrderThumb { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> OrderFee { get; set; }
        public string OrderFeeName { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public Nullable<int> OrderUpdateTime { get; set; }
        public string TradeNo { get; set; }
        public Nullable<short> add_time { get; set; }
        public Nullable<int> OrderTime { get; set; }
        public string Editor { get; set; }
        public string RefundReason { get; set; }
        public string Note { get; set; }
        public string SellerId { get; set; }
        public string SellerName { get; set; }
        public string BuyerId { get; set; }
        public string BuyerName { get; set; }
        public string BuyerQQ { get; set; }
        public string BuyerGameName { get; set; }
        public Nullable<int> BuyerLevel { get; set; }
        public string BuyerProfession { get; set; }
        public string BuyerReason { get; set; }
        public string BuyerReceive { get; set; }
        public Nullable<byte> BuyerStar { get; set; }
        public string BuyerPobile { get; set; }
        public string BuyerPhone { get; set; }
        public string BuyerPostCode { get; set; }
        public string BuyerAddress { get; set; }
        public string SendNo { get; set; }
        public string SendType { get; set; }
        public Nullable<byte> SellerStar { get; set; }
        public string SendTime { get; set; }
        public Nullable<int> SendDays { get; set; }
    }
}
