
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bayetech.DAL.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class View_ArticleInfo
{

    public long itemid { get; set; }

    public int catid { get; set; }

    public string catname { get; set; }

    public string title { get; set; }

    public string introduce { get; set; }

    public string tag { get; set; }

    public string keyword { get; set; }

    public string author { get; set; }

    public string copyfrom { get; set; }

    public string fromurl { get; set; }

    public int hits { get; set; }

    public string thumb { get; set; }

    public int addtime { get; set; }

    public string editor { get; set; }

    public int edittime { get; set; }

    public byte status { get; set; }

    public short moduleid { get; set; }

    public string modulename { get; set; }

}

}
