//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LoginInfo
    {
        public string loginip { get; set; }
        public int logintime { get; set; }
        public string message { get; set; }
        public long logid { get; set; }
        public Nullable<int> itemid { get; set; }
        public string game_user { get; set; }
        public string game_pass { get; set; }
        public string game_name { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> iphone { get; set; }
        public string email { get; set; }
        public string email_pass { get; set; }
        public string answer_1 { get; set; }
        public string tname { get; set; }
        public string security { get; set; }
        public Nullable<int> identity { get; set; }
        public string ask_3 { get; set; }
        public string id_pic { get; set; }
        public string ask_2 { get; set; }
        public string ask_1 { get; set; }
        public string answer_3 { get; set; }
        public string answer_2 { get; set; }
    }
}
