//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderInfo
    {
        public Nullable<long> GameId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string GameName { get; set; }
        public Nullable<int> GameLevel { get; set; }
        public string GameProfession { get; set; }
        public string GameService { get; set; }
        public string GameGroup { get; set; }
        public string GameServer { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public Nullable<int> EditTime { get; set; }
        public Nullable<int> AddTime { get; set; }
        public string QQLevel { get; set; }
        public string IdentityInfo { get; set; }
        public string QQFriends { get; set; }
        public long MallId { get; set; }
        public long OrderId { get; set; }
        public string OrderNo { get; set; }
        public string OrderTitle { get; set; }
        public string OrderThumb { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public string OrderFeeName { get; set; }
        public Nullable<decimal> OrderFee { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public Nullable<int> OrderUpdateTime { get; set; }
        public string SellerId { get; set; }
        public string BuyerId { get; set; }
        public string TradeNo { get; set; }
        public Nullable<int> OrderTime { get; set; }
        public string Editor { get; set; }
        public string RefundReason { get; set; }
        public string Note { get; set; }
        public string SendNo { get; set; }
        public string SendType { get; set; }
        public Nullable<byte> SellerStar { get; set; }
        public string SendTime { get; set; }
        public Nullable<int> SendDays { get; set; }
        public Nullable<long> GameAcountId { get; set; }
    }
}
