//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="IGameRoleInfoService.Auto.cs">
//		作者：Jie
//		所属工程：Bayetech2.0
//		生成时间：2017-11-17 10:44
// </copyright>
//------------------------------------------------------------------------------
using Bayetech.DAL.Entity;
namespace Bayetech.Service.IServices
{
    public partial interface IGameRoleInfoService : IBaseService<GameRoleInfo>
    {
        //自定义接口规范 请建立同名partial interface文件。防止代码被重新生成覆盖
    }
}

