//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="IModuleService.Auto.cs">
//		作者：Johny
//		所属工程：eDoctor.Services
//		生成时间：2017-10-30 16:49
// </copyright>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Bayetech.DAL.Entity;
using Bayetech.Service;

namespace Bayetech.Service.IServices
{
    public partial interface IModuleService : IBaseService<Module>
    {
        //自定义接口规范 请建立同名partial interface文件。防止代码被重新生成覆盖
    }
}

