//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string GameName { get; set; }
        public string Iphone { get; set; }
        public string Email { get; set; }
        public string EmailPass { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Ask1 { get; set; }
        public string Ask2 { get; set; }
        public string Ask3 { get; set; }
        public Nullable<int> Identity { get; set; }
        public string IdPic { get; set; }
        public string Security { get; set; }
        public string Tname { get; set; }
        public Nullable<bool> EnableMark { get; set; }
        public string AccountType { get; set; }
    }
}
