//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Sys_logs
    {
        public int KeyId { get; set; }
        public Nullable<int> OperationType { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string TableName { get; set; }
        public string BusinessName { get; set; }
        public string PrimaryKey { get; set; }
        public string SqlText { get; set; }
        public string OperationIp { get; set; }
    }
}
