//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Sys_Users
    {
        public int KeyId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PassSalt { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string TrueName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Mobile { get; set; }
        public string QQ { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string MenusJson { get; set; }
        public string ConfigJson { get; set; }
    }
}
