//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Sys_Navigations
    {
        public int KeyId { get; set; }
        public string NavTitle { get; set; }
        public string Linkurl { get; set; }
        public int Sortnum { get; set; }
        public string iconCls { get; set; }
        public string iconUrl { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string NavTag { get; set; }
        public string BigImageUrl { get; set; }
        public Nullable<bool> IsNewWindow { get; set; }
        public Nullable<int> WinWidth { get; set; }
        public Nullable<int> WinHeight { get; set; }
    }
}
