//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Sys_Area
    {
        public int KeyId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string MergerName { get; set; }
        public Nullable<int> AreaLevel { get; set; }
        public string Pinyin { get; set; }
        public string Code { get; set; }
        public string ZipCode { get; set; }
        public string First { get; set; }
        public string Lng { get; set; }
        public string Lat { get; set; }
    }
}
