//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Sys_Departments
    {
        public int KeyId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Sortnum { get; set; }
        public string Remark { get; set; }
        public string DepCode { get; set; }
        public Nullable<int> DepType { get; set; }
        public string Faren { get; set; }
        public string Tel { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> IsUse { get; set; }
        public string Addr { get; set; }
        public string OndutyPhone { get; set; }
        public string OndutyPhone2 { get; set; }
        public string ComplainPhone { get; set; }
        public string WebSite { get; set; }
        public string QQ { get; set; }
    }
}
