//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Sys_Area_bac
    {
        public int KeyId { get; set; }
        public string Title { get; set; }
        public string AreaLevel { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string AreaCode { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    }
}
