//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long catid { get; set; }
        public short moduleid { get; set; }
        public string catname { get; set; }
        public string style { get; set; }
        public string catdir { get; set; }
        public string linkurl { get; set; }
        public string letter { get; set; }
        public byte level { get; set; }
        public long item { get; set; }
        public short property { get; set; }
        public int parentid { get; set; }
        public string arrparentid { get; set; }
        public byte child { get; set; }
        public string arrchildid { get; set; }
        public short listorder { get; set; }
        public string template { get; set; }
        public string show_template { get; set; }
        public string seo_title { get; set; }
        public string seo_keywords { get; set; }
        public string seo_description { get; set; }
        public string group_list { get; set; }
        public string group_show { get; set; }
        public string group_add { get; set; }
        public string img { get; set; }
    }
}
