//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionIdentityTable
    {
        public long SurrogateIdentityId { get; set; }
        public System.Guid DefinitionIdentityHash { get; set; }
        public System.Guid DefinitionIdentityAnyRevisionHash { get; set; }
        public string Name { get; set; }
        public string Package { get; set; }
        public Nullable<long> Build { get; set; }
        public Nullable<long> Major { get; set; }
        public Nullable<long> Minor { get; set; }
        public Nullable<long> Revision { get; set; }
    }
}
