//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLRequire
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> DLPeriod { get; set; }
        public Nullable<long> GameId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> ServerId { get; set; }
        public Nullable<decimal> EfficiencyDeposit { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> QQ { get; set; }
        public Nullable<int> ValidityPeriod { get; set; }
        public string SecretCode { get; set; }
        public Nullable<decimal> Tip { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
