//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodDetail
    {
        public string GoodInfoId { get; set; }
        public Nullable<int> Lv { get; set; }
        public string Gender { get; set; }
        public Nullable<int> QQLv { get; set; }
        public Nullable<int> HasQQFriend { get; set; }
        public Nullable<int> HasIdSealedRecord { get; set; }
        public string ProfessionCode1 { get; set; }
        public string ProfessionCode2 { get; set; }
        public string ProfessionCode3 { get; set; }
    }
}
