//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstancePromotedPropertiesTable
    {
        public long SurrogateInstanceId { get; set; }
        public string PromotionName { get; set; }
        public byte[] Value33 { get; set; }
        public byte[] Value34 { get; set; }
        public byte[] Value35 { get; set; }
        public byte[] Value36 { get; set; }
        public byte[] Value37 { get; set; }
        public byte[] Value38 { get; set; }
        public byte[] Value39 { get; set; }
        public byte[] Value40 { get; set; }
        public byte[] Value41 { get; set; }
        public byte[] Value42 { get; set; }
        public byte[] Value43 { get; set; }
        public byte[] Value44 { get; set; }
        public byte[] Value45 { get; set; }
        public byte[] Value46 { get; set; }
        public byte[] Value47 { get; set; }
        public byte[] Value48 { get; set; }
        public byte[] Value49 { get; set; }
        public byte[] Value50 { get; set; }
        public byte[] Value51 { get; set; }
        public byte[] Value52 { get; set; }
        public byte[] Value53 { get; set; }
        public byte[] Value54 { get; set; }
        public byte[] Value55 { get; set; }
        public byte[] Value56 { get; set; }
        public byte[] Value57 { get; set; }
        public byte[] Value58 { get; set; }
        public byte[] Value59 { get; set; }
        public byte[] Value60 { get; set; }
        public byte[] Value61 { get; set; }
        public byte[] Value62 { get; set; }
        public byte[] Value63 { get; set; }
        public byte[] Value64 { get; set; }
    }
}
