//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallGoodInfo
    {
        public int Id { get; set; }
        public string GoodTitle { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<decimal> GoodSinglePrice { get; set; }
        public string GoodKeyWord { get; set; }
        public Nullable<long> GoodTypeId { get; set; }
        public Nullable<long> GameId { get; set; }
        public string GoodNo { get; set; }
        public string GoodDetailInfo { get; set; }
        public string GoodFirstPicture { get; set; }
        public string GameAccount { get; set; }
        public string GameService { get; set; }
        public Nullable<int> GameGroupId { get; set; }
        public Nullable<long> GameProfessionId { get; set; }
        public Nullable<int> GameServerId { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> CancelNum { get; set; }
        public string UserName { get; set; }
        public Nullable<int> HistoryAccount { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> GoldNum { get; set; }
        public string Dealway { get; set; }
        public string TradeType { get; set; }
        public Nullable<System.DateTime> GoodValidityTime { get; set; }
        public Nullable<int> QQ { get; set; }
        public string Phone { get; set; }
    }
}
