//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallDLInfo
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> SavePrice { get; set; }
        public Nullable<decimal> EfficiencyPrice { get; set; }
        public string WorkerType { get; set; }
        public string Type { get; set; }
        public string DlType { get; set; }
        public Nullable<long> GameId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> ServerId { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public Nullable<int> PeriodYears { get; set; }
        public Nullable<int> PeriodDays { get; set; }
        public Nullable<int> PeriodHours { get; set; }
        public string DlNo { get; set; }
        public string Description { get; set; }
        public Nullable<long> DLAccountId { get; set; }
        public Nullable<int> CurrentLevel { get; set; }
        public Nullable<int> TargetLevel { get; set; }
        public string CurrentProfession { get; set; }
        public string TargertProfession { get; set; }
        public string AddAbility { get; set; }
        public Nullable<bool> IsUseGameBonus { get; set; }
        public Nullable<bool> IsJoinUnion { get; set; }
        public string Phone { get; set; }
        public Nullable<int> QQ { get; set; }
        public Nullable<int> ValidityPeriod { get; set; }
        public string SecretCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
