//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oasEntities : DbContext
    {
        public oasEntities()
            : base("name=oasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_XmlConfig> SYS_XmlConfig { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Flow_Admin> T_Flow_Admin { get; set; }
        public virtual DbSet<T_Flow_BitAndItem> T_Flow_BitAndItem { get; set; }
        public virtual DbSet<T_Flow_FunctionDefault> T_Flow_FunctionDefault { get; set; }
        public virtual DbSet<T_FLOW_OperatePerm> T_FLOW_OperatePerm { get; set; }
        public virtual DbSet<T_FLOW_OperateUser> T_FLOW_OperateUser { get; set; }
        public virtual DbSet<T_Flow_OptiomItem> T_Flow_OptiomItem { get; set; }
        public virtual DbSet<T_Flow_OptiomTextItem> T_Flow_OptiomTextItem { get; set; }
        public virtual DbSet<T_FLOW_Role_CUT> T_FLOW_Role_CUT { get; set; }
        public virtual DbSet<T_FLOW_STATUS> T_FLOW_STATUS { get; set; }
        public virtual DbSet<T_Flow_StatusRole> T_Flow_StatusRole { get; set; }
        public virtual DbSet<T_Flow_Trust> T_Flow_Trust { get; set; }
        public virtual DbSet<T_FLOW_TYPE> T_FLOW_TYPE { get; set; }
        public virtual DbSet<T_Flow_Type_Bigclass> T_Flow_Type_Bigclass { get; set; }
        public virtual DbSet<T_Flow_Type_Info> T_Flow_Type_Info { get; set; }
        public virtual DbSet<T_Flow_UpdateLog> T_Flow_UpdateLog { get; set; }
        public virtual DbSet<T_Flow_WindowsClass> T_Flow_WindowsClass { get; set; }
        public virtual DbSet<T_FrameWork_Detali> T_FrameWork_Detali { get; set; }
        public virtual DbSet<T_FrameWork_Summary> T_FrameWork_Summary { get; set; }
        public virtual DbSet<T_Pro_CaseStatus> T_Pro_CaseStatus { get; set; }
        public virtual DbSet<T_Pro_Menu> T_Pro_Menu { get; set; }
        public virtual DbSet<T_Pro_MenuRole> T_Pro_MenuRole { get; set; }
        public virtual DbSet<T_Pub_Duty> T_Pub_Duty { get; set; }
        public virtual DbSet<T_Pub_Module> T_Pub_Module { get; set; }
        public virtual DbSet<T_Pub_Org> T_Pub_Org { get; set; }
        public virtual DbSet<T_Pub_Org_Member> T_Pub_Org_Member { get; set; }
        public virtual DbSet<T_Pub_Rights> T_Pub_Rights { get; set; }
        public virtual DbSet<T_Pub_Role> T_Pub_Role { get; set; }
        public virtual DbSet<T_Pub_User> T_Pub_User { get; set; }
        public virtual DbSet<t_pub_user_parents> t_pub_user_parents { get; set; }
        public virtual DbSet<T_Pub_UserRights> T_Pub_UserRights { get; set; }
        public virtual DbSet<T_Pub_UserRole> T_Pub_UserRole { get; set; }
        public virtual DbSet<T_Status_OperationRole> T_Status_OperationRole { get; set; }
        public virtual DbSet<T_STATUS_TYPE> T_STATUS_TYPE { get; set; }
        public virtual DbSet<T_WorkFlow_Assign> T_WorkFlow_Assign { get; set; }
        public virtual DbSet<T_WorkFlow_AssignBiz> T_WorkFlow_AssignBiz { get; set; }
        public virtual DbSet<T_WorkFlow_Attachments> T_WorkFlow_Attachments { get; set; }
        public virtual DbSet<T_WORKFLOW_AttCatalog> T_WORKFLOW_AttCatalog { get; set; }
        public virtual DbSet<T_WORKFLOW_AttPattern> T_WORKFLOW_AttPattern { get; set; }
        public virtual DbSet<T_WorkFlow_AttSelfReMark> T_WorkFlow_AttSelfReMark { get; set; }
        public virtual DbSet<T_WorkFlow_AttTrackChange> T_WorkFlow_AttTrackChange { get; set; }
        public virtual DbSet<T_WorkFlow_AttType> T_WorkFlow_AttType { get; set; }
        public virtual DbSet<T_WorkFlow_BalanceSeting> T_WorkFlow_BalanceSeting { get; set; }
        public virtual DbSet<T_WorkFlow_BalanceSetingHis> T_WorkFlow_BalanceSetingHis { get; set; }
        public virtual DbSet<T_WorkFlow_BalanceSetingLog> T_WorkFlow_BalanceSetingLog { get; set; }
        public virtual DbSet<T_WorkFlow_BizFollow> T_WorkFlow_BizFollow { get; set; }
        public virtual DbSet<T_WorkFlow_Diffluence> T_WorkFlow_Diffluence { get; set; }
        public virtual DbSet<T_WORKFLOW_EXCHCHANGE> T_WORKFLOW_EXCHCHANGE { get; set; }
        public virtual DbSet<T_WORKFLOW_EXCHCHANGE_TYPE> T_WORKFLOW_EXCHCHANGE_TYPE { get; set; }
        public virtual DbSet<T_WORKFLOW_FLOWEXPAND> T_WORKFLOW_FLOWEXPAND { get; set; }
        public virtual DbSet<t_WorkFlow_FlowInfo> t_WorkFlow_FlowInfo { get; set; }
        public virtual DbSet<T_WorkFlow_FlowMain> T_WorkFlow_FlowMain { get; set; }
        public virtual DbSet<T_WorkFlow_GlobalData> T_WorkFlow_GlobalData { get; set; }
        public virtual DbSet<T_WorkFlow_LogFLOWEXPAND> T_WorkFlow_LogFLOWEXPAND { get; set; }
        public virtual DbSet<T_WorkFlow_LogFlowMain> T_WorkFlow_LogFlowMain { get; set; }
        public virtual DbSet<T_WorkFlow_LogMainAtt> T_WorkFlow_LogMainAtt { get; set; }
        public virtual DbSet<T_WorkFlow_LogMainField> T_WorkFlow_LogMainField { get; set; }
        public virtual DbSet<T_WorkFlow_LogMonitor> T_WorkFlow_LogMonitor { get; set; }
        public virtual DbSet<T_WorkFlow_LogNotify> T_WorkFlow_LogNotify { get; set; }
        public virtual DbSet<T_WorkFlow_LogPrint> T_WorkFlow_LogPrint { get; set; }
        public virtual DbSet<T_WorkFlow_LogZaiBan> T_WorkFlow_LogZaiBan { get; set; }
        public virtual DbSet<T_WorkFlow_MainAtt> T_WorkFlow_MainAtt { get; set; }
        public virtual DbSet<T_WorkFlow_MainField> T_WorkFlow_MainField { get; set; }
        public virtual DbSet<T_WorkFlow_Notify> T_WorkFlow_Notify { get; set; }
        public virtual DbSet<T_WorkFlow_Number> T_WorkFlow_Number { get; set; }
        public virtual DbSet<T_WorkFlow_PageChange> T_WorkFlow_PageChange { get; set; }
        public virtual DbSet<T_WorkFlow_SelfRemark> T_WorkFlow_SelfRemark { get; set; }
        public virtual DbSet<T_WorkFlow_ZaiBan> T_WorkFlow_ZaiBan { get; set; }
        public virtual DbSet<TWF_TCB_Estate> TWF_TCB_Estate { get; set; }
        public virtual DbSet<TWF_TCB_Exchange> TWF_TCB_Exchange { get; set; }
        public virtual DbSet<TWF_TCB_Property> TWF_TCB_Property { get; set; }
        public virtual DbSet<T_FLOW_DISPOSAL> T_FLOW_DISPOSAL { get; set; }
        public virtual DbSet<T_Flow_FormLimit> T_Flow_FormLimit { get; set; }
        public virtual DbSet<T_FLOW_Type_20180311> T_FLOW_Type_20180311 { get; set; }
        public virtual DbSet<T_FLOW_UI> T_FLOW_UI { get; set; }
        public virtual DbSet<T_INSTANCE_FLOW_DISPOSAL> T_INSTANCE_FLOW_DISPOSAL { get; set; }
        public virtual DbSet<T_INSTANCE_FLOW_STATUS> T_INSTANCE_FLOW_STATUS { get; set; }
        public virtual DbSet<T_Pro_Menu_new> T_Pro_Menu_new { get; set; }
        public virtual DbSet<T_Pro_MenuRole_new> T_Pro_MenuRole_new { get; set; }
        public virtual DbSet<T_Status_OperationPerm> T_Status_OperationPerm { get; set; }
        public virtual DbSet<t_WorkFlow_FlowInfo2> t_WorkFlow_FlowInfo2 { get; set; }
        public virtual DbSet<T_WORKFLOW_PARENTID> T_WORKFLOW_PARENTID { get; set; }
        public virtual DbSet<T_WorkFlow_ROLEIDEA> T_WorkFlow_ROLEIDEA { get; set; }
        public virtual DbSet<T_Flow_Role> T_Flow_Role { get; set; }
        public virtual DbSet<T_flow_UserRole> T_flow_UserRole { get; set; }
        public virtual DbSet<t_pub_company> t_pub_company { get; set; }
        public virtual DbSet<t_pub_dept> t_pub_dept { get; set; }
        public virtual DbSet<V_FLOW_ROLE> V_FLOW_ROLE { get; set; }
        public virtual DbSet<V_Flow_StatusUser> V_Flow_StatusUser { get; set; }
        public virtual DbSet<V_Flow_StatusUserAll> V_Flow_StatusUserAll { get; set; }
        public virtual DbSet<v_flow_user> v_flow_user { get; set; }
        public virtual DbSet<v_framework_main> v_framework_main { get; set; }
        public virtual DbSet<v_framework_notify> v_framework_notify { get; set; }
        public virtual DbSet<v_framework_zaiban> v_framework_zaiban { get; set; }
        public virtual DbSet<v_pub_member_org> v_pub_member_org { get; set; }
        public virtual DbSet<V_PUB_MEMBER_USER> V_PUB_MEMBER_USER { get; set; }
        public virtual DbSet<v_pub_org> v_pub_org { get; set; }
        public virtual DbSet<v_pub_user> v_pub_user { get; set; }
        public virtual DbSet<v_pub_user_member> v_pub_user_member { get; set; }
        public virtual DbSet<v_pub_user_parents> v_pub_user_parents { get; set; }
        public virtual DbSet<V_WorkFlow_FlowMain> V_WorkFlow_FlowMain { get; set; }
        public virtual DbSet<V_WorkFlow_Notify> V_WorkFlow_Notify { get; set; }
        public virtual DbSet<V_WorkFlow_OtherAttDetail> V_WorkFlow_OtherAttDetail { get; set; }
        public virtual DbSet<V_WorkFlow_ZaiBan> V_WorkFlow_ZaiBan { get; set; }
    }
}
