//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunnableInstancesTable
    {
        public long SurrogateInstanceId { get; set; }
        public Nullable<System.Guid> WorkflowHostType { get; set; }
        public Nullable<long> ServiceDeploymentId { get; set; }
        public System.DateTime RunnableTime { get; set; }
        public long SurrogateIdentityId { get; set; }
    }
}
