//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_XmlConfig
    {
        public long ID { get; set; }
        public string SysType { get; set; }
        public string XmlConfig { get; set; }
        public Nullable<int> IsNew { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> drecordTime { get; set; }
    }
}
