//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FLOW_TYPE
    {
        public decimal FLOW_ID { get; set; }
        public decimal Company_ID { get; set; }
        public string FLOW_NAME { get; set; }
        public string WordDot { get; set; }
        public string WINDOWS_CLASS { get; set; }
        public Nullable<decimal> AUTO_PRESS_TIME { get; set; }
        public Nullable<decimal> NORMAL_DESTINE_TIME { get; set; }
        public Nullable<decimal> DISPATCH_DESTINE_TIME { get; set; }
        public Nullable<decimal> URGENCY_DESTINE_TIME { get; set; }
        public Nullable<decimal> SUPERFINE_DESTINE_TIME { get; set; }
        public Nullable<int> Is_Special { get; set; }
        public Nullable<decimal> Example_Limit { get; set; }
        public string UI_Url { get; set; }
        public string Flow_Type_Name { get; set; }
        public Nullable<decimal> RecordDept_Id { get; set; }
        public string Remark { get; set; }
        public string Flow_Attribute { get; set; }
        public Nullable<int> sortorder { get; set; }
        public Nullable<int> Flow_Type_Bigclass_Id { get; set; }
        public Nullable<int> comProperty { get; set; }
        public string BU_NAME { get; set; }
        public bool linelimit { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string FlowType { get; set; }
        public string OutStanding { get; set; }
    }
}
