//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_Role
    {
        public long userrole_id { get; set; }
        public Nullable<decimal> company_id { get; set; }
        public string userrole_name { get; set; }
        public string userrole_remark { get; set; }
        public string userrole_column { get; set; }
        public string userrole_display { get; set; }
        public int isOtherRole { get; set; }
        public decimal id { get; set; }
        public string role_code { get; set; }
    }
}
