//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_FunctionDefault
    {
        public string Fn_Code { get; set; }
        public string Fn_Name { get; set; }
        public string Fn_Catalog { get; set; }
        public string Fn_Description { get; set; }
        public int Fn_OrderBy { get; set; }
        public string Fn_ShowType { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    }
}
