//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_flow_UserRole
    {
        public string User_id { get; set; }
        public long UserRoleColumn1 { get; set; }
        public Nullable<long> UserRoleColumn2 { get; set; }
        public Nullable<long> UserRoleColumn3 { get; set; }
        public Nullable<long> UserRoleColumn4 { get; set; }
        public Nullable<long> UserRoleColumn5 { get; set; }
        public Nullable<long> UserRoleColumn6 { get; set; }
        public Nullable<long> UserRoleColumn7 { get; set; }
    }
}
