//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_UpdateLog
    {
        public long id { get; set; }
        public string MachineName { get; set; }
        public string User_Id { get; set; }
        public decimal Company_Id { get; set; }
        public string Company_Name { get; set; }
        public decimal Flow_Id { get; set; }
        public string Flow_Name { get; set; }
        public decimal Operate_DateTime { get; set; }
        public int Operate_Id { get; set; }
        public decimal OperateObject_Id { get; set; }
        public string OperateObject_Name { get; set; }
        public Nullable<bool> Invalid { get; set; }
        public string Operate_BeforeState { get; set; }
        public string Operate_AfterState { get; set; }
    }
}
