//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_Type_Bigclass
    {
        public int Flow_Type_Bigclass_Id { get; set; }
        public string Flow_Type_Bigclass_Name { get; set; }
        public Nullable<int> FlowType_GroupId { get; set; }
        public string FlowType_GroupName { get; set; }
        public string Img_Url { get; set; }
        public int SortOrder { get; set; }
        public string Flow_Type_Remark { get; set; }
        public Nullable<bool> ISSHOW { get; set; }
    }
}
