//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_BitAndItem
    {
        public string Item_Key { get; set; }
        public long Item_Value { get; set; }
        public string Item_Name { get; set; }
        public int Item_Type { get; set; }
        public string Item_Remark { get; set; }
        public int Item_Sort { get; set; }
        public string DefaultCode { get; set; }
    }
}
