//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_WindowsClass
    {
        public string windows_class { get; set; }
        public string chinesename { get; set; }
        public string ui_url { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> FLOW_ID { get; set; }
    }
}
