//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Flow_StatusRole
    {
        public decimal Status_Id { get; set; }
        public decimal Flow_Id { get; set; }
        public Nullable<long> UserRoleColumn1 { get; set; }
        public Nullable<long> UserRoleColumn2 { get; set; }
        public Nullable<long> UserRoleColumn3 { get; set; }
        public Nullable<long> UserRoleColumn4 { get; set; }
        public Nullable<long> UserRoleColumn5 { get; set; }
    }
}
