//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FLOW_STATUS
    {
        public decimal STATUS_ID { get; set; }
        public decimal FLOW_ID { get; set; }
        public Nullable<decimal> STATUS_TYPE_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public string INTERFLOW_CUSTOM_RULE { get; set; }
        public Nullable<decimal> CUR_X { get; set; }
        public Nullable<decimal> CUR_Y { get; set; }
        public string INTERFIX_FIELD { get; set; }
        public string COM_EXTEND { get; set; }
        public string CHILD_FLOW_TYPE { get; set; }
        public string CHILD_FLOW_HINT { get; set; }
        public string CHILD_FLOW { get; set; }
        public string CHANGE_FLOW_NAME { get; set; }
        public string CHANGE_STATUS_NAME { get; set; }
        public string AUTO_FIELD_LIST { get; set; }
        public string AUTO_CUSTOM_RULE { get; set; }
        public string AUTO_FIELD_NAME { get; set; }
        public string INTERFLOW_UNITE_LIST { get; set; }
        public Nullable<int> userrole_ID { get; set; }
        public Nullable<decimal> CHANGE_FLOW_ID { get; set; }
        public Nullable<decimal> CHANGE_STATUS_ID { get; set; }
        public Nullable<int> FrontFor_Limit { get; set; }
        public Nullable<decimal> OperationRole_ID { get; set; }
        public string UI_Url { get; set; }
        public Nullable<decimal> Child_Flow_Combine { get; set; }
        public Nullable<decimal> isNextStatus { get; set; }
        public string Status_Attribute { get; set; }
        public int IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public int status_order { get; set; }
        public int status_level { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int SupportType { get; set; }
        public string STATUS_CODE { get; set; }
    }
}
