//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FrameWork_Summary
    {
        public string WfmId { get; set; }
        public string RootId { get; set; }
        public string TradeType { get; set; }
        public string TradeProperty { get; set; }
        public string CaseNum { get; set; }
        public string BranchNum { get; set; }
        public string CompanyNum { get; set; }
        public string PropertyName { get; set; }
        public string FullAddress { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string OrgId { get; set; }
        public string OrgName { get; set; }
        public string OwnerName { get; set; }
        public string ClientName { get; set; }
        public string CommonMoneyType { get; set; }
        public Nullable<decimal> CommonMoney { get; set; }
        public string FinanceMark { get; set; }
        public int IsFromFirst { get; set; }
        public int PDeal { get; set; }
        public int isShare { get; set; }
    }
}
