//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FrameWork_Detali
    {
        public string WfmId { get; set; }
        public string ReceiptNum { get; set; }
        public string CredenceCode { get; set; }
        public string PayMethod { get; set; }
        public string SaveBank { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string PayMan { get; set; }
        public string ReceiveMan { get; set; }
        public string ReceiveBank { get; set; }
        public string ReceiveAccount { get; set; }
        public string BillType { get; set; }
        public string NonCorpIncomeType { get; set; }
        public Nullable<decimal> NonCorpIncome { get; set; }
        public string PayUsage { get; set; }
        public Nullable<int> ContractEnd { get; set; }
        public Nullable<decimal> AnJieMoney { get; set; }
        public Nullable<decimal> LayMoney { get; set; }
        public string NewProperty { get; set; }
    }
}
