//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INSTANCE_FLOW_DISPOSAL
    {
        public decimal DISPOSAL_ID { get; set; }
        public decimal FLOW_ID { get; set; }
        public string DISPOSAL_HINT { get; set; }
        public string DISPOSAL_NAME { get; set; }
        public Nullable<decimal> TRANSACT_STATUS_ID { get; set; }
        public Nullable<decimal> DEPT_LIMIT { get; set; }
        public Nullable<decimal> ROLE_LIMIT { get; set; }
        public decimal CUR_STATUS_ID { get; set; }
        public decimal PRE_STATUS_ID { get; set; }
        public string FLOW_INS_ID { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Action_Content { get; set; }
    }
}
