//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INSTANCE_FLOW_STATUS
    {
        public string FLOW_INS_ID { get; set; }
        public decimal FLOW_ID { get; set; }
        public decimal COMPANY_ID { get; set; }
        public string FLOW_NAME { get; set; }
        public string WINDOWS_CLASS { get; set; }
        public string UI_URL { get; set; }
        public decimal STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public string INTERFLOW_CUSTOM_RULE { get; set; }
        public string CHILD_FLOW_TYPE { get; set; }
        public string CHILD_FLOW_HINT { get; set; }
        public string CHILD_FLOW { get; set; }
        public string CHANGE_FLOW_NAME { get; set; }
        public Nullable<decimal> CHANGE_FLOW_ID { get; set; }
        public string CHANGE_STATUS_NAME { get; set; }
        public Nullable<decimal> CHANGE_STATUS_ID { get; set; }
        public string INTERFLOW_UNITE_LIST { get; set; }
        public Nullable<decimal> OPERATIONROLE_ID { get; set; }
        public Nullable<decimal> CHILD_FLOW_COMBINE { get; set; }
        public Nullable<decimal> ISNEXTSTATUS { get; set; }
        public decimal STATUS_TYPE_ID { get; set; }
        public string STATUS_TYPE_NAME { get; set; }
        public string Status_Attribute { get; set; }
    }
}
