//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pro_Menu_new
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string url { get; set; }
        public Nullable<int> sortid { get; set; }
        public string Remark { get; set; }
        public string SysFlag { get; set; }
        public string ModuleId { get; set; }
        public Nullable<int> isdelete { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
