//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pro_MenuRole
    {
        public long ID { get; set; }
        public long MenuID { get; set; }
        public long RoleValue { get; set; }
        public long RoleColumn1 { get; set; }
        public Nullable<long> RoleColumn2 { get; set; }
        public System.DateTime createtime { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public string moduleID { get; set; }
    }
}
