//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pub_company
    {
        public decimal company_id { get; set; }
        public Nullable<decimal> parent_id { get; set; }
        public string company_name { get; set; }
        public string company_display { get; set; }
        public string company_gb { get; set; }
        public Nullable<decimal> company_level { get; set; }
        public Nullable<decimal> company_order { get; set; }
        public string adspath { get; set; }
        public string isshow { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string telephone { get; set; }
        public string address { get; set; }
        public string company_code { get; set; }
        public string remark { get; set; }
    }
}
