//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pub_Role
    {
        public decimal Role_id { get; set; }
        public long Role_Value { get; set; }
        public string Module_ID { get; set; }
        public Nullable<decimal> Company_ID { get; set; }
        public string Role_Display { get; set; }
        public string Role_Name { get; set; }
        public string Role_Remark { get; set; }
        public string Role_Column { get; set; }
        public System.DateTime? CreateTime { get; set; }
        public string RoleSerial { get; set; }
    }
}
