//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pub_dept
    {
        public Nullable<decimal> company_id { get; set; }
        public decimal dept_id { get; set; }
        public Nullable<decimal> Parent_ID { get; set; }
        public string dept_name { get; set; }
        public string dept_type { get; set; }
        public Nullable<decimal> org_level { get; set; }
        public Nullable<decimal> dept_order { get; set; }
        public string dept_display { get; set; }
        public string dept_gb { get; set; }
        public string Dept_EN { get; set; }
        public string Dept_Water { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string asspath { get; set; }
        public string ISShow { get; set; }
        public string dept_code { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsVirtual { get; set; }
    }
}
