//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pub_Org
    {
        public decimal Org_id { get; set; }
        public Nullable<decimal> Parent_ID { get; set; }
        public string Org_Code { get; set; }
        public string Org_GB { get; set; }
        public string Org_Display { get; set; }
        public string Org_Name { get; set; }
        public Nullable<int> Manage_Type { get; set; }
        public string Org_Guid { get; set; }
        public Nullable<decimal> Org_Level_id { get; set; }
        public Nullable<decimal> Org_Order { get; set; }
        public string Org_Type { get; set; }
        public string ADPath { get; set; }
        public string ISShow { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string Dept_EN { get; set; }
        public string Dept_Water { get; set; }
        public Nullable<int> IsVirtual { get; set; }
        public Nullable<decimal> Filter { get; set; }
        public Nullable<int> IsBehindLeader { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string GUID_Path { get; set; }
        public string addition { get; set; }
        public string K3FullName { get; set; }
        public string K3Guid { get; set; }
        public string K3Name { get; set; }
        public string k3HROCCode { get; set; }
    }
}
