//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pub_UserRole
    {
        public decimal Userrole_id { get; set; }
        public string User_id { get; set; }
        public string Module_ID { get; set; }
        public long Role_value { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<long> RoleColumn1 { get; set; }
        public Nullable<long> RoleColumn2 { get; set; }
        public Nullable<long> RoleColumn3 { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    }
}
