//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pub_Module
    {
        public string Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Display { get; set; }
        public string CataLogId { get; set; }
        public Nullable<decimal> IsCatalog { get; set; }
        public Nullable<decimal> IsShow { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> msrepl_tran_version { get; set; }
    }
}
