//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Status_OperationRole
    {
        public int OperationRole_ID { get; set; }
        public string Windows_Class { get; set; }
        public string OperationRole_Name { get; set; }
        public int OperationPerm_ID { get; set; }
        public string OperationRole_Remark { get; set; }
    }
}
