//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_PageChange
    {
        public string GUID { get; set; }
        public string WFM_ID { get; set; }
        public string SourceString { get; set; }
        public string TargetString { get; set; }
        public string Root_ID { get; set; }
        public Nullable<decimal> Flow_ID { get; set; }
        public Nullable<decimal> Status_ID { get; set; }
        public string User_ID { get; set; }
        public string DisplayName { get; set; }
        public int IsNew { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    }
}
