//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_WorkFlow_FlowInfo2
    {
        public long Id { get; set; }
        public string parentID { get; set; }
        public string wfmid { get; set; }
        public string TradeProperty { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public string ZCJName { get; set; }
        public string ZJUserID { get; set; }
        public string ZCJDept { get; set; }
        public Nullable<int> ZJDeptID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> DaiLiLv { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> CompanyIncome { get; set; }
        public Nullable<decimal> zhuanJie { get; set; }
        public Nullable<decimal> ZhuanJieLv { get; set; }
        public Nullable<decimal> TuoZhanRate { get; set; }
        public Nullable<decimal> ZhongJieRate { get; set; }
        public Nullable<decimal> XiangMuRate { get; set; }
        public Nullable<decimal> AnJie { get; set; }
        public string JumpWfmid { get; set; }
        public Nullable<long> PageConditionRule2 { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public System.DateTime drecordTime { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<long> PropertyID { get; set; }
    }
}
