//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_MainField
    {
        public string WFM_ID { get; set; }
        public string Fields { get; set; }
        public int reportFlag { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<System.DateTime> drecordTime { get; set; }
        public string SysFlag { get; set; }
    }
}
