//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_ROLEIDEA
    {
        public string WRD_ID { get; set; }
        public string Role_NAME { get; set; }
        public string Role_IDEAR { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public string User_ID { get; set; }
        public System.DateTime WriteDate { get; set; }
        public int Disp_ID { get; set; }
        public string WFM_ID { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    }
}
