//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORKFLOW_FLOWEXPAND
    {
        public string WFM_ID { get; set; }
        public int Disp_ID { get; set; }
        public string PassedStatus { get; set; }
        public string VerilyPassedStatus { get; set; }
        public string PassedUserCode { get; set; }
        public string PassedUserID { get; set; }
        public string PassedOrgPath { get; set; }
        public System.DateTime FirstCheckOutTime { get; set; }
        public System.DateTime CheckOutTime { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public System.DateTime CheckAction { get; set; }
        public string WFRootID { get; set; }
        public long StartFlag { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public decimal ownerOrgId { get; set; }
        public string ownerUserId { get; set; }
        public string ownerUserCode { get; set; }
        public string printAddress { get; set; }
        public string CpnyIncomeMoney { get; set; }
        public string CpnyIncomeType { get; set; }
        public string RootFlowCode { get; set; }
        public string DistrictName { get; set; }
        public string ownerOrgCode { get; set; }
        public string ownerOrgName { get; set; }
        public string ownerUserName { get; set; }
        public string ownerName { get; set; }
        public string clientName { get; set; }
        public string estatename { get; set; }
        public string proAddr { get; set; }
        public string ExchangeType { get; set; }
        public string CheckOutUser { get; set; }
        public string PayBank { get; set; }
        public string PayMode { get; set; }
        public string CredenceCode { get; set; }
        public string LastRoleIdea { get; set; }
        public Nullable<System.DateTime> BizPassedTime1 { get; set; }
        public Nullable<System.DateTime> BizPassedTime2 { get; set; }
        public Nullable<System.DateTime> BizPassedTime3 { get; set; }
        public Nullable<System.DateTime> BizPassedTime4 { get; set; }
        public Nullable<System.DateTime> BizPassedTime5 { get; set; }
        public Nullable<System.DateTime> BizPassedTime6 { get; set; }
        public Nullable<System.DateTime> BizPassedTime7 { get; set; }
        public Nullable<int> BizPassedTimeFlag { get; set; }
        public string FundFullCode { get; set; }
        public string PageFullCode { get; set; }
        public string CompanyFullCode { get; set; }
        public string UserDefaultColumn1 { get; set; }
        public string UserDefaultColumn2 { get; set; }
        public string UserDefaultColumn3 { get; set; }
        public string UserDefaultColumn4 { get; set; }
        public string UserDefaultColumn5 { get; set; }
        public System.DateTime UserDefaultDateTime1 { get; set; }
        public System.DateTime UserDefaultDateTime2 { get; set; }
        public System.DateTime UserDefaultDateTime3 { get; set; }
        public System.DateTime UserDefaultDateTime4 { get; set; }
        public System.DateTime UserDefaultDateTime5 { get; set; }
        public int UserDefaultDateTimeFlag { get; set; }
        public int isLoanChanged { get; set; }
        public Nullable<long> OldStartFlag { get; set; }
        public string caseType { get; set; }
        public string FundTitle { get; set; }
        public Nullable<decimal> commissionAmount { get; set; }
        public string sourceFlag { get; set; }
        public string yxPropStatusId { get; set; }
        public string LDClientGuid { get; set; }
        public string LDClientName { get; set; }
        public string LDDealCode { get; set; }
    }
}
