//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_LogPrint
    {
        public string Guid { get; set; }
        public string wfm_id { get; set; }
        public string changnumid { get; set; }
        public string kpmanid { get; set; }
        public string printmessage { get; set; }
        public System.DateTime pdatetime { get; set; }
        public string xmltext { get; set; }
        public string compip { get; set; }
        public string compname { get; set; }
        public string printid { get; set; }
        public string PrintName { get; set; }
        public string WinUserName { get; set; }
    }
}
