//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_BalanceSeting
    {
        public string GUID { get; set; }
        public System.DateTime BS_StartTime { get; set; }
        public System.DateTime BS_EndTime { get; set; }
        public System.DateTime BS_UseTime { get; set; }
        public int BS_UseFlag { get; set; }
        public int BS_SortOrder { get; set; }
        public int BS_StartFlag { get; set; }
        public int BS_Year { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    }
}
