//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORKFLOW_AttCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_WORKFLOW_AttCatalog()
        {
            this.T_WorkFlow_Attachments = new HashSet<T_WorkFlow_Attachments>();
            this.T_WORKFLOW_AttPattern = new HashSet<T_WORKFLOW_AttPattern>();
        }
    
        public string wacc_code { get; set; }
        public string wacc_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_WorkFlow_Attachments> T_WorkFlow_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_WORKFLOW_AttPattern> T_WORKFLOW_AttPattern { get; set; }
    }
}
