//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORKFLOW_EXCHCHANGE
    {
        public string WFM_ID { get; set; }
        public int EXT_ID { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public string EX_DESC { get; set; }
        public int PushState { get; set; }
        public string dUserId { get; set; }
        public Nullable<System.DateTime> dRecordTime { get; set; }
    
        public virtual T_WORKFLOW_EXCHCHANGE_TYPE T_WORKFLOW_EXCHCHANGE_TYPE { get; set; }
    }
}
