//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORKFLOW_EXCHCHANGE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_WORKFLOW_EXCHCHANGE_TYPE()
        {
            this.T_WORKFLOW_EXCHCHANGE = new HashSet<T_WORKFLOW_EXCHCHANGE>();
        }
    
        public int EXT_ID { get; set; }
        public string EXT_NAME { get; set; }
        public string EXT_DESC { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_WORKFLOW_EXCHCHANGE> T_WORKFLOW_EXCHCHANGE { get; set; }
    }
}
