//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_Attachments
    {
        public string WFM_ID { get; set; }
        public string FATT_ID { get; set; }
        public string ATT_NAME { get; set; }
        public string ATT_PATH { get; set; }
        public int Disp_ID { get; set; }
        public string ATT_Catalog { get; set; }
        public int IsWaster { get; set; }
        public int IsAlid { get; set; }
        public System.DateTime upload_Date { get; set; }
        public string upload_user_id { get; set; }
        public string watp_code { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public string Remark { get; set; }
        public int LockFlag { get; set; }
        public string AttType_Name { get; set; }
        public string Parent_Id { get; set; }
        public Nullable<int> PageCount { get; set; }
        public string PageOrder { get; set; }
        public string ServerPath { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        public virtual T_WORKFLOW_AttCatalog T_WORKFLOW_AttCatalog { get; set; }
    }
}
