//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_LogMonitor
    {
        public string WFM_ID { get; set; }
        public int Disp_ID { get; set; }
        public Nullable<decimal> CURSTATUS_ID { get; set; }
        public string CURSTATUS_Name { get; set; }
        public Nullable<decimal> PRESTATUS_ID { get; set; }
        public string PRESTATUS_Name { get; set; }
        public Nullable<decimal> DISPOSAL_ID { get; set; }
        public string DISPOSAL_Name { get; set; }
        public string DISPOSAL_HINT { get; set; }
        public string DealRemark { get; set; }
        public string Sender { get; set; }
        public string SenderName { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public string SenderTrust { get; set; }
        public string ReceiverTrust { get; set; }
        public string SenderTrustName { get; set; }
        public string ReceiverTrustName { get; set; }
        public System.DateTime ArriveTime { get; set; }
        public System.DateTime FinishTime { get; set; }
        public int DealState { get; set; }
        public string DealStateName { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public string CURRole_Name { get; set; }
        public long CURRole_ID { get; set; }
        public string PRERole_Name { get; set; }
        public long PRERole_ID { get; set; }
        public string ID { get; set; }
        public string PassStatusUserId { get; set; }
    }
}
