//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_LogZaiBan
    {
        public string WZB_ID { get; set; }
        public string Executor { get; set; }
        public string ExecutorName { get; set; }
        public string TRANSACTOR { get; set; }
        public string TRANSACTORNAME { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public long Transact_Role { get; set; }
        public decimal DEALSTATUS_TYPE_ID { get; set; }
        public string DEALSTATUS_TYPE_NAME { get; set; }
        public Nullable<decimal> DEALSTATUS_ID { get; set; }
        public string DEALSTATUS_NAME { get; set; }
        public int Transact_Type { get; set; }
        public string WFM_ID { get; set; }
        public int Disp_ID { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public string GUID { get; set; }
        public string PassedStatus_Code { get; set; }
        public string RoleCode { get; set; }
    }
}
