//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_BizFollow
    {
        public string WF_BF_ID { get; set; }
        public decimal Flow_ID { get; set; }
        public string WFM_ID { get; set; }
        public string Intent { get; set; }
        public string folcontent { get; set; }
        public string suggest { get; set; }
        public string folmethod { get; set; }
        public string copmethod { get; set; }
        public System.DateTime foltime { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public string user_id { get; set; }
        public decimal org_id { get; set; }
        public decimal duty_id { get; set; }
        public string coopfolman { get; set; }
    }
}
