//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WorkFlow_Number
    {
        public string BN_GUID { get; set; }
        public string BN_WFM_ID { get; set; }
        public string BN_ROOT_ID { get; set; }
        public string BN_FullCode { get; set; }
        public string BN_CodeParam1 { get; set; }
        public string BN_CodeParam2 { get; set; }
        public string BN_CodeParam3 { get; set; }
        public string BN_CodeParam4 { get; set; }
        public string BN_CodeParam5 { get; set; }
        public string BN_CodeParam6 { get; set; }
        public string BN_CodeParam7 { get; set; }
        public string BN_CodeParam8 { get; set; }
        public string BN_CodeParam9 { get; set; }
        public Nullable<decimal> BN_CodeIndex1 { get; set; }
        public Nullable<decimal> BN_CodeIndex2 { get; set; }
        public Nullable<decimal> BN_CodeIndex3 { get; set; }
        public Nullable<int> BN_CodeParamInt1 { get; set; }
        public Nullable<int> BN_CodeParamInt2 { get; set; }
        public Nullable<int> BN_CodeParamInt3 { get; set; }
        public Nullable<int> BN_CodeIndex1Length { get; set; }
        public Nullable<int> BN_CodeIndex2Length { get; set; }
        public Nullable<int> BN_CodeIndex3Length { get; set; }
        public Nullable<decimal> BN_Flow_ID { get; set; }
        public string BN_Flow_Code { get; set; }
        public string BN_CodeGroup { get; set; }
        public string BN_WINDOWS_CLASS { get; set; }
        public Nullable<int> BN_CodeYear { get; set; }
        public int BN_CodeMonth { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
        public string BN_DisplayCode { get; set; }
        public int BN_IsWaster { get; set; }
        public int BN_CodeType { get; set; }
    }
}
