//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TWF_TCB_Exchange
    {
        public string WFM_ID { get; set; }
        public string Case_WFM_ID { get; set; }
        public int EstateValue { get; set; }
        public string Exchange_Type { get; set; }
        public string Exchange_Value { get; set; }
        public Nullable<decimal> Org_ID { get; set; }
        public string Org_Name { get; set; }
        public string BizUser_ID { get; set; }
        public string BizUser_Name { get; set; }
        public string @operator { get; set; }
        public string operatorName { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    }
}
