//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TWF_TCB_Property
    {
        public string WFM_ID { get; set; }
        public string Case_WFM_ID { get; set; }
        public string PropertyID { get; set; }
        public string EstateID { get; set; }
        public int DISP_ID { get; set; }
        public string CityName { get; set; }
        public string DistrictName { get; set; }
        public string AreaName { get; set; }
        public string EstateName { get; set; }
        public string Address { get; set; }
        public string RoomNo { get; set; }
        public string Spell { get; set; }
        public string ProAddr { get; set; }
        public int Case_Estate { get; set; }
        public string Case_Owner { get; set; }
        public string Case_OwnerName { get; set; }
        public string BizUser_ID { get; set; }
        public string BizUser_Name { get; set; }
        public string BizOrg_ID { get; set; }
        public string BizOrg_Name { get; set; }
        public System.DateTime Intent_Date { get; set; }
        public System.DateTime Earnest_Date { get; set; }
        public System.DateTime Signup_Date { get; set; }
        public System.DateTime Change_Date { get; set; }
        public System.DateTime Blowdown_Date { get; set; }
        public System.DateTime EndCase_Date { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string sRecordVersion { get; set; }
    }
}
