//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_flow_user
    {
        public decimal Org_id { get; set; }
        public Nullable<decimal> Org_Parent { get; set; }
        public string Org_Code { get; set; }
        public string Org_GB { get; set; }
        public string Org_Display { get; set; }
        public string Org_Name { get; set; }
        public string Org_Guid { get; set; }
        public Nullable<decimal> Org_Level_id { get; set; }
        public Nullable<decimal> Org_Order { get; set; }
        public string Org_Type { get; set; }
        public string Org_ADPath { get; set; }
        public string Org_Mail { get; set; }
        public string Org_Fax { get; set; }
        public string Org_Address { get; set; }
        public string Org_Remark { get; set; }
        public string Dept_EN { get; set; }
        public string Org_Telephone { get; set; }
        public string Dept_Water { get; set; }
        public Nullable<int> IsVirtual { get; set; }
        public Nullable<int> IsBehindLeader { get; set; }
        public string Org_GUID_Path { get; set; }
        public string User_ID { get; set; }
        public string User_Parent { get; set; }
        public string User_Guid { get; set; }
        public Nullable<decimal> UserRole_Value { get; set; }
        public Nullable<int> IsAvailab { get; set; }
        public string User_DisplayName { get; set; }
        public string User_Code { get; set; }
        public Nullable<decimal> Duty_ID { get; set; }
        public string User_Name { get; set; }
        public string User_PWD { get; set; }
        public Nullable<decimal> User_SEX { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile { get; set; }
        public string Office_Phone1 { get; set; }
        public string Office_Address { get; set; }
        public string Office_Phone2 { get; set; }
        public string User_Fax { get; set; }
        public string User_Email { get; set; }
        public string Http_Addr { get; set; }
        public string User_Resume { get; set; }
        public string Home_Addr { get; set; }
        public string UnderWrite { get; set; }
        public string User_Remark { get; set; }
        public Nullable<decimal> IsAdmin { get; set; }
        public Nullable<decimal> OrderBy { get; set; }
        public string User_ADPath { get; set; }
        public string RndCode { get; set; }
        public Nullable<decimal> IsTempUser { get; set; }
        public Nullable<int> Leaderflag { get; set; }
        public string User_Type { get; set; }
        public string User_Guid_Path { get; set; }
        public Nullable<decimal> HasCert { get; set; }
        public Nullable<decimal> Company_ID { get; set; }
        public string duty_name { get; set; }
        public Nullable<decimal> Dept_ID { get; set; }
    }
}
