//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Flow_StatusUserBack
    {
        public Nullable<decimal> Company_ID { get; set; }
        public string User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_DisplayName { get; set; }
        public string User_Code { get; set; }
        public string Parent_ID { get; set; }
        public string Parent_Name { get; set; }
        public string Parent_DisplayName { get; set; }
        public Nullable<decimal> OrderBy { get; set; }
        public long userrole_id { get; set; }
        public string userrole_name { get; set; }
        public string userrole_display { get; set; }
        public string userrole_column { get; set; }
        public Nullable<decimal> Org_ID { get; set; }
        public string Org_GB { get; set; }
        public string Org_Name { get; set; }
        public string Org_Display { get; set; }
        public Nullable<decimal> Org_Level_id { get; set; }
        public Nullable<decimal> Org_Order { get; set; }
        public string Org_Code { get; set; }
        public string GUID_Path { get; set; }
        public decimal Status_Id { get; set; }
        public decimal Flow_Id { get; set; }
        public decimal id { get; set; }
        public Nullable<decimal> IsTempUser { get; set; }
    }
}
