//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FLOW_ROLE
    {
        public long UserRole_ID { get; set; }
        public Nullable<decimal> Company_ID { get; set; }
        public string UserRole_Display { get; set; }
        public string USERROLE_Column { get; set; }
        public string UserRole_Remark { get; set; }
        public int isOtherRole { get; set; }
    }
}
