//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_framework_main
    {
        public string WFM_ID { get; set; }
        public string Title { get; set; }
        public decimal Flow_ID { get; set; }
        public decimal FlowType { get; set; }
        public string Flow_Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public int IsFinish { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string ModifyFlag { get; set; }
        public Nullable<int> SubFinished { get; set; }
        public string SpeciID { get; set; }
        public string ParentID { get; set; }
        public bool IsSigned { get; set; }
        public bool IsWaster_ { get; set; }
        public string LockUserID { get; set; }
        public Nullable<bool> IS_Pigeonhole { get; set; }
        public int TransFlag { get; set; }
        public string HuanJi { get; set; }
        public string PassedStatus { get; set; }
        public decimal ownerOrgId { get; set; }
        public string ownerUserId { get; set; }
        public string ownerUserCode { get; set; }
        public string user_name { get; set; }
        public string org_name { get; set; }
        public string org_code { get; set; }
        public string WFRootID { get; set; }
        public long StartFlag { get; set; }
        public System.DateTime CheckAction { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public System.DateTime CheckOutTime { get; set; }
        public string owner_name { get; set; }
        public string clientName { get; set; }
        public string RootFlowCode { get; set; }
        public string estatename { get; set; }
        public string proAddr { get; set; }
        public long BizEstate { get; set; }
        public Nullable<decimal> CURSTATUS_ID { get; set; }
        public string CURSTATUS_NAME { get; set; }
        public string ExchangeType { get; set; }
        public string VerilyPassedStatus { get; set; }
        public string PayBank { get; set; }
        public string PayMode { get; set; }
        public int DealFolder { get; set; }
        public string CredenceCode { get; set; }
        public string FundFullCode { get; set; }
        public string CompanyFullCode { get; set; }
        public string PageFullCode { get; set; }
        public string UserDefaultColumn3 { get; set; }
        public string UserDefaultColumn4 { get; set; }
        public string LastRoleIdea { get; set; }
        public System.DateTime UserDefaultDateTime1 { get; set; }
        public int UserDefaultDateTimeFlag { get; set; }
        public System.DateTime BalanceTime { get; set; }
        public System.DateTime BalanceUseTime { get; set; }
        public int BalanceValid { get; set; }
        public int isLoanChanged { get; set; }
        public string sourceFlag { get; set; }
        public string LDClientGuid { get; set; }
        public string LDClientName { get; set; }
        public string LDDealCode { get; set; }
    }
}
