//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_framework_notify
    {
        public string WFM_ID { get; set; }
        public string Title { get; set; }
        public decimal Flow_ID { get; set; }
        public decimal FlowType { get; set; }
        public string Flow_Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public int IsFinish { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string ModifyFlag { get; set; }
        public Nullable<int> SubFinished { get; set; }
        public string SpeciID { get; set; }
        public string ParentID { get; set; }
        public bool IsSigned { get; set; }
        public bool IsWaster_ { get; set; }
        public string LockUserID { get; set; }
        public Nullable<bool> IS_Pigeonhole { get; set; }
        public int TransFlag { get; set; }
        public string HuanJi { get; set; }
        public long BizEstate { get; set; }
        public Nullable<decimal> CURSTATUS_ID { get; set; }
        public string CURSTATUS_NAME { get; set; }
        public int DealFolder { get; set; }
        public System.DateTime BalanceTime { get; set; }
        public System.DateTime BalanceUseTime { get; set; }
        public int BalanceValid { get; set; }
        public string WNT_ID { get; set; }
        public string Executor { get; set; }
        public string ExecutorName { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public string Sender { get; set; }
        public string SenderName { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public int IsShow { get; set; }
        public Nullable<int> IsTempSave { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string Name { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Disp_ID { get; set; }
        public int DelayLimit { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public string OrderDiscountName { get; set; }
        public string OrderType { get; set; }
        public string ReceiveRole { get; set; }
        public Nullable<System.DateTime> OrderUpdateTime { get; set; }
        public string GoodNo { get; set; }
        public string ServiceId { get; set; }
        public Nullable<long> ServiceQQ { get; set; }
        public string BuyerId { get; set; }
        public Nullable<long> BuyerPhone { get; set; }
        public Nullable<int> InternalTypeId { get; set; }
        public Nullable<long> BuyerQQ { get; set; }
        public string GoodType { get; set; }
        public Nullable<System.DateTime> OrderCreatTime { get; set; }
        public string PromoNum { get; set; }
        public string Editor { get; set; }
        public string RefundReason { get; set; }
        public string Remark { get; set; }
        public string OrderStatus { get; set; }
        public string BuyTypeCode { get; set; }
        public Nullable<int> OrderLineNum { get; set; }
    }
}
