//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_framework_zaiban
    {
        public string WFM_ID { get; set; }
        public string Title { get; set; }
        public decimal Flow_ID { get; set; }
        public decimal FlowType { get; set; }
        public string Flow_Name { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public int IsFinish { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string ModifyFlag { get; set; }
        public Nullable<int> SubFinished { get; set; }
        public string SpeciID { get; set; }
        public string ParentID { get; set; }
        public bool IsSigned { get; set; }
        public bool IsWaster_ { get; set; }
        public string LockUserID { get; set; }
        public Nullable<bool> IS_Pigeonhole { get; set; }
        public int TransFlag { get; set; }
        public string huanji { get; set; }
        public string PassedStatus { get; set; }
        public decimal ownerOrgId { get; set; }
        public string ownerUserId { get; set; }
        public string ownerUserCode { get; set; }
        public string user_name { get; set; }
        public string org_name { get; set; }
        public string org_code { get; set; }
        public string WFRootID { get; set; }
        public long StartFlag { get; set; }
        public System.DateTime CheckAction { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public System.DateTime CheckOutTime { get; set; }
        public string owner_name { get; set; }
        public string clientName { get; set; }
        public string RootFlowCode { get; set; }
        public string EstateName { get; set; }
        public string ProAddr { get; set; }
        public long BizEstate { get; set; }
        public Nullable<decimal> CURSTATUS_ID { get; set; }
        public string CURSTATUS_NAME { get; set; }
        public string ExchangeType { get; set; }
        public string VerilyPassedStatus { get; set; }
        public string paybank { get; set; }
        public string paymode { get; set; }
        public int DealFolder { get; set; }
        public string CredenceCode { get; set; }
        public string FundFullCode { get; set; }
        public string CompanyFullCode { get; set; }
        public string PageFullCode { get; set; }
        public string UserDefaultColumn3 { get; set; }
        public string UserDefaultColumn4 { get; set; }
        public string lastroleidea { get; set; }
        public System.DateTime UserDefaultDateTime1 { get; set; }
        public int UserDefaultDateTimeFlag { get; set; }
        public System.DateTime BalanceTime { get; set; }
        public System.DateTime BalanceUseTime { get; set; }
        public int BalanceValid { get; set; }
        public string WZB_ID { get; set; }
        public string TRANSACTOR { get; set; }
        public string TRANSACTORNAME { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public int Transact_Type { get; set; }
        public long Transact_Role { get; set; }
        public System.DateTime dRecordCreationDate { get; set; }
        public string sRecordCreator { get; set; }
        public string PassedStatus_Code { get; set; }
        public string Name { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Disp_ID { get; set; }
    }
}
