//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_pub_user_parents
    {
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string User_code { get; set; }
        public string duty_name { get; set; }
        public string IsTempUser { get; set; }
        public string P1_User_id { get; set; }
        public string P1_User_NAME { get; set; }
        public string P1_User_code { get; set; }
        public string P1_duty_name { get; set; }
        public string P2_User_id { get; set; }
        public string P2_User_NAME { get; set; }
        public string P2_User_code { get; set; }
        public string p2_duty_name { get; set; }
        public string P3_User_id { get; set; }
        public string P3_User_NAME { get; set; }
        public string P3_User_code { get; set; }
        public string p3_duty_name { get; set; }
        public string P4_User_id { get; set; }
        public string P4_User_NAME { get; set; }
        public string P4_User_code { get; set; }
        public string p4_duty_name { get; set; }
        public string P5_User_id { get; set; }
        public string P5_User_NAME { get; set; }
        public string P5_User_code { get; set; }
        public string p5_duty_name { get; set; }
        public string P6_User_id { get; set; }
        public string P6_User_NAME { get; set; }
        public string P6_User_code { get; set; }
        public string p6_duty_name { get; set; }
    }
}
