//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WorkFlow_OtherAttDetail
    {
        public string WFM_ID { get; set; }
        public string ATT_Catalog { get; set; }
        public string wacc_name { get; set; }
        public string watp_code { get; set; }
        public string watp_name { get; set; }
        public int IsWaster { get; set; }
        public int IsAlid { get; set; }
        public int LockFlag { get; set; }
        public string ATT_NAME { get; set; }
    }
}
