//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MallDLOrderInfo
    {
        public long OrderId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderLineNum { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public string OrderDiscountName { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderUpdateTime { get; set; }
        public string OrderType { get; set; }
        public string ReceiveRole { get; set; }
        public string ServiceId { get; set; }
        public Nullable<long> ServiceQQ { get; set; }
        public string BuyerId { get; set; }
        public Nullable<long> BuyerPhone { get; set; }
        public Nullable<long> BuyerQQ { get; set; }
        public Nullable<int> InternalTypeId { get; set; }
        public string GoodType { get; set; }
        public Nullable<System.DateTime> OrderCreatTime { get; set; }
        public string StatusName { get; set; }
        public string StatusAlias { get; set; }
        public string key { get; set; }
        public string Value { get; set; }
        public string Title { get; set; }
        public string TimeDiff { get; set; }
        public string WorkAlias { get; set; }
        public string WorkIntroduce { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<decimal> SavePrice { get; set; }
        public Nullable<decimal> EfficiencyPrice { get; set; }
        public string WorkerType { get; set; }
        public Nullable<long> GameId { get; set; }
        public string DlType { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> ServerId { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public Nullable<int> PeriodDays { get; set; }
        public Nullable<int> PeriodHours { get; set; }
        public Nullable<int> PeriodYears { get; set; }
        public string Description { get; set; }
        public Nullable<long> Id { get; set; }
        public string GoodNo { get; set; }
        public string GroupName { get; set; }
        public string ServerName { get; set; }
        public string GameAward { get; set; }
        public string GameName { get; set; }
        public string DlTypeName { get; set; }
        public string SocietyUnion { get; set; }
        public Nullable<int> Order { get; set; }
        public string Unit { get; set; }
    }
}
