//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MallGoodMainInfo
    {
        public string GoodTitle { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<decimal> GoodSinglePrice { get; set; }
        public string GoodKeyWord { get; set; }
        public Nullable<long> GameId { get; set; }
        public string GoodNo { get; set; }
        public string GameService { get; set; }
        public Nullable<int> GameGroupId { get; set; }
        public Nullable<int> GameServerId { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> HistoryAccount { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string GroupName { get; set; }
        public string ServerName { get; set; }
        public string GameName { get; set; }
        public string GoodTypeName { get; set; }
        public string GameAccount { get; set; }
        public Nullable<int> CancelNum { get; set; }
        public string GoodDetailInfo { get; set; }
        public string GoodFirstPicture { get; set; }
        public Nullable<long> GoodTypeId { get; set; }
        public string ProfessionName { get; set; }
        public Nullable<long> ProfessionId { get; set; }
        public string Status { get; set; }
        public string StatusName { get; set; }
        public string BackName { get; set; }
        public string FrontName { get; set; }
        public Nullable<int> FrontParentId { get; set; }
        public Nullable<int> BackParentId { get; set; }
        public string Remark { get; set; }
        public string SalerId { get; set; }
        public string ProfessionCode1 { get; set; }
        public string ProfessionCode2 { get; set; }
        public string ProfessionCode3 { get; set; }
        public Nullable<int> Lv { get; set; }
        public string Gender { get; set; }
        public Nullable<int> QQLv { get; set; }
        public Nullable<int> HasQQFriend { get; set; }
        public Nullable<int> HasIdSealedRecord { get; set; }
    }
}
