//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MallDLInfo
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string WorkerType { get; set; }
        public string DlType { get; set; }
        public Nullable<long> GameId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> ServerId { get; set; }
        public string TimeDiff { get; set; }
        public Nullable<int> PeriodYears { get; set; }
        public Nullable<int> PeriodDays { get; set; }
        public Nullable<int> PeriodHours { get; set; }
        public string GoodNo { get; set; }
        public string Description { get; set; }
        public string DLAlias { get; set; }
        public string DLIntroduce { get; set; }
        public string WorkAlias { get; set; }
        public string WorkIntroduce { get; set; }
    }
}
