//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bayetech.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MallGoodInfo
    {
        public string GoodTitle { get; set; }
        public string GoodKeyWord { get; set; }
        public Nullable<long> GoodType { get; set; }
        public Nullable<long> GameId { get; set; }
        public string GoodNo { get; set; }
        public string GameName { get; set; }
        public string GameService { get; set; }
        public Nullable<int> GameGroupId { get; set; }
        public Nullable<int> GameServerId { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ListOrder { get; set; }
        public Nullable<int> HistoryAccount { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<long> DescriptionId { get; set; }
        public string DescriptionValue { get; set; }
        public string DescriptionName { get; set; }
        public int Id { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
