//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="ArticleService.Auto.cs">
//		作者：Jie
//		所属工程：Bayetech2.0
//		生成时间：2017-11-17 10:47
// </copyright>
//------------------------------------------------------------------------------
using Bayetech.DAL.Entity;
using Bayetech.Service.IServices;
namespace Bayetech.Service.Services 
{

    public partial class ArticleService :ServiceBase<Article>,IArticleService
    {    
        //自定义接口实现请建立同名partial class文件。防止代码被重新生成覆盖
    }
}

